<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['storage_app_description'] = 'The Storage Manager allows you to map large data shares to storage volumes.';
$lang['storage_app_name'] = 'Storage Manager';
$lang['storage_big_picture'] = 'Big Picture';
$lang['storage_bootable'] = 'Bootable';
$lang['storage_create_data_drive'] = 'Create Data Drive';
$lang['storage_creating_store_point'] = 'Creating store point';
$lang['storage_device'] = 'Device';
$lang['storage_device_invalid'] = 'Device is invalid.';
$lang['storage_devices'] = 'Devices';
$lang['storage_file_system'] = 'File System';
$lang['storage_file_system_type_invalid'] = 'File system type is invalid.';
$lang['storage_in_use'] = 'In Use';
$lang['storage_initializing_storage_warning'] = 'Initializing storage... this may take a few minutes.';
$lang['storage_inline_help_overview'] = 'Many apps require significant storage space for user data: web proxy caches, network shares and databases are just some examples.  The Storage Manager provides a way to isolate this user data on a seperate partition.';
$lang['storage_linux_extended'] = 'Linux Extended';
$lang['storage_lvm'] = 'LVM';
$lang['storage_mapping'] = 'Mapping';
$lang['storage_mappings'] = 'Mappings';
$lang['storage_model'] = 'Model';
$lang['storage_mount'] = 'Mount';
$lang['storage_mount_point'] = 'Mount Point';
$lang['storage_mounting_store:'] = 'Mounting store:';
$lang['storage_partitions'] = 'Partitions';
$lang['storage_size'] = 'Size';
$lang['storage_source'] = 'Source';
$lang['storage_source_already_has_mount_point:'] = 'Source already has mount point:';
$lang['storage_source_folder_does_not_exist:'] = 'Source folder does not exist:';
$lang['storage_source_folder_non_empty:'] = 'Source folder is non-empty:';
$lang['storage_storage'] = 'Storage';
$lang['storage_storage_base_does_not_exist:'] = 'Storage base does not exist:';
$lang['storage_storage_manager_guide'] = 'Storage Manager Guide';
$lang['storage_store'] = 'Store';
$lang['storage_store_active'] = 'Storage active.';
$lang['storage_store_mount_failed:'] = 'Storage mount_failed:';
$lang['storage_swap'] = 'Swap';
$lang['storage_user_guide_preamble'] = 'By default, the /store directory is used for mounting storage. For more information or just general tips and tricks, please follow the link to User Guide.';
$lang['storage_wizard_help'] = 'If you plan on storing a significant amount of data on a separate partition or storage target, please stop right here and take a moment to read the help in the sidebar!  If you skip this step, it becomes a big chore to move data around later.';
