<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['storage_app_description'] = 'Manager magazynu danych pozwala na zmapowanie dużych udziałów sieciowych do woluminów magazynowania.';
$lang['storage_app_name'] = 'Manager magazynu danych';
$lang['storage_big_picture'] = 'Duży obraz';
$lang['storage_bootable'] = 'Rozruchowy';
$lang['storage_create_data_drive'] = 'Utwórz dysk danych';
$lang['storage_creating_store_point'] = 'Tworzenie punktu przechowywania';
$lang['storage_device'] = 'Urządzenie';
$lang['storage_device_invalid'] = 'Nazwa urządzenia jest nieprawidłowa.';
$lang['storage_devices'] = 'Urządzenia';
$lang['storage_file_system'] = 'System plików';
$lang['storage_file_system_type_invalid'] = 'Typ systemu plików jest nieprawidłowy.';
$lang['storage_in_use'] = 'W użyciu';
$lang['storage_initializing_storage_warning'] = 'Inicjalizuję magazyn danych... to może zająć kilka minut';
$lang['storage_inline_help_overview'] = 'Wiele aplikacji wymaga sporej ilości miejsca w magazynie danych na dane użytkownika: bufor serwera proxy, udziały sieciowe czy bazy danych to tylko niektóre przykłady.  Manager magazynu danych oferuje możliwość izolacji tych danych użytkownika na oddzielnej partycji.';
$lang['storage_linux_extended'] = 'Partycja rozszerzona systemu Linux';
$lang['storage_lvm'] = 'LVM';
$lang['storage_mapping'] = 'Mapowanie';
$lang['storage_mappings'] = 'Mapowania';
$lang['storage_model'] = 'Model';
$lang['storage_mount'] = 'Zamontuj';
$lang['storage_mount_point'] = 'Punkt montowania';
$lang['storage_mounting_store:'] = 'Miejsce montowania';
$lang['storage_partitions'] = 'Partycje';
$lang['storage_size'] = 'Rozmiar';
$lang['storage_source'] = 'Lokalizacja źródłowa';
$lang['storage_source_already_has_mount_point:'] = 'Lokalizacja źródłowa posiada już punkt montowania:';
$lang['storage_source_folder_does_not_exist:'] = 'Folder źródłowy nie istnieje:';
$lang['storage_source_folder_non_empty:'] = 'Folder źródłowy nie jest pusty:';
$lang['storage_storage'] = 'Magazyn danych';
$lang['storage_storage_base_does_not_exist:'] = 'Bazowy magazyn danych nie istnieje:';
$lang['storage_storage_manager_guide'] = 'Przewodnik po magazynie danych';
$lang['storage_store'] = 'Przechowaj';
$lang['storage_store_active'] = 'Aktywny magazyn danych.';
$lang['storage_store_mount_failed:'] = 'Nie udało się zamontować magazynu danych:';
$lang['storage_swap'] = 'Partycja Swap';
$lang['storage_user_guide_preamble'] = 'Domyślnie, folder /store używany jest do montowania magazynu danych. Aby uzyskać więcej informacji lub ogólnych porad i wskazówek, proszę kliknąć w link do Przewodnika Użytkownika.';
$lang['storage_wizard_help'] = 'Jeżeli planujesz przechowywać dużą ilość danych na oddzielnej partycji lub w docelowym magazynie danych, zatrzymaj się w tym miejscu i poświęć chwilę na przeczytanie tekstu pomocy z panelu bocznego!  Jeżeli ominiesz ten krok, to później będziesz miał dużo pracy z przenoszeniem danych.';
